version: "2.2"
services:

  nifi:
    image: apache/nifi:1.15.3
    ports:
      - "8443:8443"
    volumes:
      - "./nifi-data:/opt/nifi/nifi-current/ls-target"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=letadminintonifi
    depends_on:
      - nifi-registry
    links:
      - "nifi-registry:nifireg"

  nifi-registry:
    image: apache/nifi-registry:1.15.3
    ports:
      - "18080:18080"
